### PR TITLE
feat: add graphql codegen, archive example

### PR DESCRIPTION
**Pull request by larwaa**
## Proposed Changes

- Add [GraphQL Codegen](https://www.graphql-code-generator.com) for automatically generating TS types for GraphQL types.
- Refactor Archive to utilize GraphQL Codegen files
- In order to update types, simply run `yarn generate` in `/frontend`

## Motivation
- Accurately typing GraphQL types is error prone, boring, and will often lead to inconsistencies. GraphQL Codegen solves this by just generating the types automatically from our schema, and using the Documents exported, we no longer have to manually type the data for `useQuery`.

## To do
- [x] Figure a nice way of generating these automatically for builds
- [x] Add "generated" alias

## Types of Changes

- [ ] New feature
- [ ] Bug fix
- [ ] Enhancement/optimization
- [ ] Refactor
- [ ] Style
- [x] Build/dependencies
- [ ] Other

## Issue(s) fixed or closed by this PR

-

## Checklist

- [ ] I have added tests to cover my changes (for features/bugs)
- [x] I am pleased with the readability of the code (if not, state where you need input)
- [x] I have tested the changes and verified that they work and do not break anything (to the best of my ability)

### CODE REVIEW

**Comment by MorganFH** [comment]
Looks good. FYI my work on introducing gql codegen last year can still be found in the branch `experimental/codegen`. After comparing a little, one thing I added that you have not, is the following lines to `codegen.yml`:

```
hooks:
  afterAllFileWrite:
    - eslint --fix
    - prettier --write
```
Which (if i remember correctly) will prettify the autogenerated file.

Additionally, I started adding fragments and updating queries/mutations to conform with codegen last year (see `src/api/graphql` in the branch I mentioned), but a lot of this is probably outdated now..

**Comment by larwaa** [comment]
> Looks good. FYI my work on introducing gql codegen last year can still be found in the branch `experimental/codegen`. After comparing a little, one thing I added that you have not, is the following lines to `codegen.yml`:
> 
> ```
> hooks:
>   afterAllFileWrite:
>     - eslint --fix
>     - prettier --write
> ```
> 
> Which (if i remember correctly) will prettify the autogenerated file.
> 
> Additionally, I started adding fragments and updating queries/mutations to conform with codegen last year (see `src/api/graphql` in the branch I mentioned), but a lot of this is probably outdated now..

I will definitely add the hooks!. Was the structure required last year by codegen, or was that a design decision on our part?

**Comment by MorganFH** [comment]
> > Looks good. FYI my work on introducing gql codegen last year can still be found in the branch `experimental/codegen`. After comparing a little, one thing I added that you have not, is the following lines to `codegen.yml`:
> > ```
> > hooks:
> >   afterAllFileWrite:
> >     - eslint --fix
> >     - prettier --write
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Which (if i remember correctly) will prettify the autogenerated file.
> > Additionally, I started adding fragments and updating queries/mutations to conform with codegen last year (see `src/api/graphql` in the branch I mentioned), but a lot of this is probably outdated now..
> 
> I will definitely add the hooks!. Was the structure required last year by codegen, or was that a design decision on our part?

The structure was just inspired by a [medium article](https://medium.com/swlh/how-to-configure-react-apollo-client-and-graphql-codegen-to-do-work-for-you-ecb305d983aa), not very thought through.

**Review by MorganFH — APPROVED** [review]
LGTM

**Pull request merged**
