### PR TITLE
✨ feat: consistent title for pages

### PR DESCRIPTION
**Pull request by larwaa**
## Proposed Changes

- Add a reusable `Title` component. Can be used with background images, a light or dark mode for normal/admin uses.
- Makes `Book nå` more prominent on `/cabins` and add price info at the top.
- Apply the reusable component to most pages
  - Event details are missing. Haven't quite decided what to do with the `Meld på` button, and if the title component should support such actions.

### First draft
Screenshot 2022-06-15 at 20 27 28

### Second draft
Screenshot 2022-06-16 at 01 03 37

Screenshot 2022-06-16 at 01 04 17

Would love some input on the cabins page. My concern, after receiving some feedback from a few people, is that the "book now" button isn't obvious enough when it's on top of the image

@einmid 

## Types of Changes

- [x] New feature
- [ ] Bug fix
- [ ] Enhancement/optimization
- [x] Refactor
- [ ] Style
- [ ] Build/dependencies
- [ ] Other

## Issue(s) fixed or closed by this PR

- Closes #

## Checklist

- [ ] I have added tests to cover my changes (for features/bugs)
- [ ] I am pleased with the readability of the code (if not, state where you need input)
- [ ] I have tested the changes and verified that they work and do not break anything (to the best of my ability)

### CODE REVIEW

**Comment by einmid** [comment]
- Agreed, this layout would make the `Book nå` pop more
- `Vi har ledige hytter` could be replaced with `Priser` or something else. The current title might not be true, especially for external guests. If title is `Priser`, `Eksternpris:`++ could be replaced with `Ekstern:`
- Use `Intern` and `Ekstern` on all prices, not mixed with `Indøk`/`Ikke-indøk`

**Comment by larwaa** [comment]
> * Agreed, this layout would make the `Book nå` pop more
> * Bringing prices up top makes a lot of sense
> * `Vi har ledige hytter` could be replaced with `Priser` or something else. The current title might not be true, especially for external guests. If title is `Priser`, `Eksternpris:`++ could be replaced with `Ekstern:`
> * Use `Intern` and `Ekstern` on all prices, not mixed with `Indøk`/`Ikke-indøk`

Great input here, I'll make some changes!

**Comment by mathiasraa** [comment]
Great changes!

One thing: title color remains dark in dark mode.
image

**Comment by larwaa** [comment]
> Great changes!
> 
> One thing: title color remains dark in dark mode. image

Fixed in 5ac2d51

**Pull request merged**
